import Link from 'next/link';
import { ArrowUpRight, Check, Clock3, PlayCircle, Plus } from 'lucide-react';
import { requireUser } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';

type ReviewRow = { id: string; status: string; created_at: string; parent_review_id: string | null; videos: { original_filename: string }[] | null; professional_services: { gig_title: string; display_name: string }[] | null };
const title = (review: ReviewRow) => review.professional_services?.[0]?.gig_title || review.videos?.[0]?.original_filename || 'Cricket review';
const coach = (review: ReviewRow) => review.professional_services?.[0]?.display_name || 'Your coach';

export default async function ReviewsPage() {
  const player = await requireUser();
  const db = await createClient();
  const { data } = await db.from('review_requests').select('id,status,created_at,parent_review_id,videos(original_filename),professional_services(gig_title,display_name)').eq('requester_id', player.id).order('created_at', { ascending: false });
  const reviews = (data || []) as ReviewRow[];
  const ready = reviews.filter(review => review.status === 'COMPLETED' && !review.parent_review_id);
  const active = reviews.filter(review => review.status !== 'COMPLETED' && !review.parent_review_id);
  const followUps = reviews.filter(review => review.parent_review_id);

  return <div className="mx-auto max-w-5xl pb-20">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Coaching feedback</p><h1 className="page-title mt-2">My reviews</h1><p className="page-copy">Your videos, coach feedback and next steps in one place.</p></div><Link href="/professionals" className="primary-button"><Plus className="mr-1.5 size-3.5" />Book a coach</Link></header>

    {ready[0] ? <Link href={`/reviews/${ready[0].id}`} className="group mt-8 block overflow-hidden rounded-[28px] border border-black/[.08] bg-neutral-900 p-6 text-white shadow-[0_20px_60px_rgba(0,0,0,.12)] transition hover:-translate-y-0.5 active:scale-[.99] motion-reduce:transform-none"><div className="flex flex-wrap items-start justify-between gap-5"><div><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-400/15 px-3 py-1.5 text-[11px] font-semibold text-emerald-300"><Check className="size-3.5" />New feedback ready</span><h2 className="mt-5 text-2xl font-semibold tracking-tight">{title(ready[0])}</h2><p className="mt-2 text-sm text-white/65">{coach(ready[0])} has finished reviewing your video.</p></div><span className="grid size-11 place-items-center rounded-full bg-white text-black transition group-hover:scale-105"><ArrowUpRight className="size-5" /></span></div><div className="mt-7 flex items-center gap-2 text-xs text-white/55"><PlayCircle className="size-4" />Watch the annotated video</div></Link> : null}

    {active.length ? <section className="mt-8"><div className="flex items-center justify-between"><div><p className="eyebrow">In progress</p><h2 className="section-title mt-2">With your coach</h2></div><span className="rounded-full bg-neutral-100 px-3 py-1.5 text-xs font-medium text-neutral-600">{active.length}</span></div><div className="mt-4 space-y-3">{active.map(review => <Link key={review.id} href={`/reviews/${review.id}`} className="group flex items-center justify-between gap-4 rounded-[22px] border border-black/[.07] bg-white/80 p-5 shadow-[0_8px_24px_rgba(0,0,0,.035)] transition hover:bg-white hover:shadow-[0_12px_30px_rgba(0,0,0,.06)] active:scale-[.995]"><div className="flex min-w-0 items-center gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-amber-50 text-amber-700"><Clock3 className="size-5" /></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{title(review)}</p><p className="mt-1 truncate text-xs text-neutral-500">{coach(review)} · Sent {new Date(review.created_at).toLocaleDateString()}</p></div></div><span className="shrink-0 text-xs font-medium text-neutral-500 transition group-hover:text-neutral-900">View</span></Link>)}</div></section> : null}

    <section className="mt-10"><div className="flex items-center justify-between"><div><p className="eyebrow">Your library</p><h2 className="section-title mt-2">Completed reviews</h2></div>{ready.length > 0 && <span className="rounded-full bg-neutral-100 px-3 py-1.5 text-xs font-medium text-neutral-600">{ready.length}</span>}</div>{ready.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{ready.map(review => <Link key={review.id} href={`/reviews/${review.id}`} className="group rounded-[22px] border border-black/[.07] bg-white/80 p-5 shadow-[0_8px_24px_rgba(0,0,0,.035)] transition hover:bg-white hover:shadow-[0_12px_30px_rgba(0,0,0,.06)] active:scale-[.99]"><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><Check className="size-4" /></span><ArrowUpRight className="size-4 text-neutral-400 transition group-hover:text-neutral-900" /></div><p className="mt-7 text-sm font-semibold">{title(review)}</p><p className="mt-1 text-xs text-neutral-500">{coach(review)} · {new Date(review.created_at).toLocaleDateString()}</p></Link>)}</div> : <div className="mt-4 rounded-[24px] border border-dashed border-black/[.12] bg-white/55 p-8 text-center"><p className="text-sm font-semibold">No completed reviews yet</p><p className="mt-2 text-xs text-neutral-500">Book a coach to get a detailed review of your cricket video.</p><Link href="/professionals" className="quiet-button mt-5">Explore coaches</Link></div>}</section>

    {followUps.length ? <section className="mt-10"><p className="eyebrow">Follow-ups</p><div className="mt-3 flex flex-wrap gap-2">{followUps.map(review => <Link key={review.id} href={`/reviews/${review.id}`} className="rounded-full border border-black/[.08] bg-white px-4 py-2 text-xs font-medium text-neutral-600 transition hover:bg-neutral-50">{title(review)} · {review.status.replaceAll('_', ' ').toLowerCase()}</Link>)}</div></section> : null}
  </div>;
}
