-- Framewise complete Supabase schema. Run once in the Supabase SQL Editor.
create extension if not exists pgcrypto;
create type public.app_role as enum ('USER','PROFESSIONAL','ADMIN');
create type public.video_status as enum ('UPLOADING','READY','PROCESSING','FAILED','DELETED');
create type public.analysis_type as enum ('AI','PROFESSIONAL');
create type public.order_status as enum ('DRAFT','SUBMITTED','QUEUED','IN_PROGRESS','COMPLETED','FAILED','CANCELLED');
create type public.assignment_status as enum ('ASSIGNED','ACCEPTED','IN_PROGRESS','SUBMITTED','DECLINED');
create type public.comment_type as enum ('POSITIVE','IMPROVEMENT','IMPORTANT','GENERAL');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,email text not null,full_name text,avatar_url text,role public.app_role not null default 'USER',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.videos (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,original_filename text not null,storage_key text not null unique,mime_type text not null,file_size bigint not null check(file_size >= 0),duration_seconds integer check(duration_seconds >= 0),thumbnail_url text,status public.video_status not null default 'UPLOADING',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table public.analysis_orders (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,video_id uuid not null references public.videos(id) on delete restrict,analysis_type public.analysis_type not null,status public.order_status not null default 'DRAFT',professional_id uuid references public.profiles(id) on delete set null,title text not null,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),completed_at timestamptz);
create table public.analyses (id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.analysis_orders(id) on delete cascade,overall_score numeric(3,1) check(overall_score between 0 and 10),summary text,strengths text[] not null default '{}',improvements text[] not null default '{}',report_json jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.professional_profiles (id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.profiles(id) on delete cascade,headline text,bio text,specialties text[] not null default '{}',years_experience integer check(years_experience >= 0),approved boolean not null default false,rating numeric(3,2) check(rating between 0 and 5),reviews_completed integer not null default 0 check(reviews_completed >= 0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.professional_assignments (id uuid primary key default gen_random_uuid(),analysis_order_id uuid not null unique references public.analysis_orders(id) on delete cascade,professional_id uuid not null references public.profiles(id) on delete cascade,status public.assignment_status not null default 'ASSIGNED',assigned_at timestamptz not null default now(),accepted_at timestamptz,submitted_at timestamptz);
create table public.timestamp_comments (id uuid primary key default gen_random_uuid(),analysis_id uuid not null references public.analyses(id) on delete cascade,professional_id uuid not null references public.profiles(id) on delete cascade,timestamp_seconds integer not null check(timestamp_seconds >= 0),title text not null,comment text not null,comment_type public.comment_type not null default 'GENERAL',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,message text not null,type text not null default 'GENERAL',read boolean not null default false,related_order_id uuid references public.analysis_orders(id) on delete set null,created_at timestamptz not null default now());
create index videos_user_idx on public.videos(user_id) where deleted_at is null; create index orders_user_idx on public.analysis_orders(user_id); create index orders_professional_idx on public.analysis_orders(professional_id); create index assignments_professional_idx on public.professional_assignments(professional_id); create index notifications_user_idx on public.notifications(user_id,read);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='ADMIN') $$;
create or replace function public.is_assigned_professional(order_uuid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.professional_assignments pa join public.professional_profiles pp on pp.user_id=pa.professional_id where pa.analysis_order_id=order_uuid and pa.professional_id=auth.uid() and pp.approved) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create trigger profiles_updated before update on public.profiles for each row execute procedure public.set_updated_at(); create trigger videos_updated before update on public.videos for each row execute procedure public.set_updated_at(); create trigger orders_updated before update on public.analysis_orders for each row execute procedure public.set_updated_at(); create trigger analyses_updated before update on public.analyses for each row execute procedure public.set_updated_at(); create trigger pros_updated before update on public.professional_profiles for each row execute procedure public.set_updated_at(); create trigger comments_updated before update on public.timestamp_comments for each row execute procedure public.set_updated_at();
-- Role changes are admin-only. The user may update personal profile fields but cannot promote themselves.
create or replace function public.protect_profile_role() returns trigger language plpgsql as $$ begin if new.role is distinct from old.role and not public.is_admin() then raise exception 'Only admins may change roles'; end if; return new; end; $$;
create trigger profile_role_guard before update on public.profiles for each row execute procedure public.protect_profile_role();

alter table public.profiles enable row level security; alter table public.videos enable row level security; alter table public.analysis_orders enable row level security; alter table public.analyses enable row level security; alter table public.professional_profiles enable row level security; alter table public.professional_assignments enable row level security; alter table public.timestamp_comments enable row level security; alter table public.notifications enable row level security;
create policy profiles_read on public.profiles for select using(id=auth.uid() or public.is_admin()); create policy profiles_update on public.profiles for update using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy videos_read on public.videos for select using(user_id=auth.uid() or public.is_admin() or exists(select 1 from public.analysis_orders o where o.video_id=id and public.is_assigned_professional(o.id))); create policy videos_write on public.videos for insert with check(user_id=auth.uid()); create policy videos_update on public.videos for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy orders_read on public.analysis_orders for select using(user_id=auth.uid() or public.is_admin() or public.is_assigned_professional(id)); create policy orders_create on public.analysis_orders for insert with check(user_id=auth.uid() and exists(select 1 from public.videos v where v.id=video_id and v.user_id=auth.uid())); create policy orders_update on public.analysis_orders for update using(user_id=auth.uid() or public.is_admin() or public.is_assigned_professional(id)) with check(user_id=auth.uid() or public.is_admin() or public.is_assigned_professional(id));
create policy analyses_read on public.analyses for select using(public.is_admin() or exists(select 1 from public.analysis_orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_assigned_professional(o.id)))); create policy analyses_write on public.analyses for all using(public.is_admin() or public.is_assigned_professional(order_id)) with check(public.is_admin() or public.is_assigned_professional(order_id));
create policy pros_read on public.professional_profiles for select using(user_id=auth.uid() or public.is_admin()); create policy pros_write on public.professional_profiles for insert with check(user_id=auth.uid()); create policy pros_update on public.professional_profiles for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy assignments_read on public.professional_assignments for select using(professional_id=auth.uid() or public.is_admin()); create policy assignments_update on public.professional_assignments for update using(professional_id=auth.uid() or public.is_admin()) with check(professional_id=auth.uid() or public.is_admin()); create policy assignments_admin_write on public.professional_assignments for insert with check(public.is_admin());
create policy comments_read on public.timestamp_comments for select using(public.is_admin() or professional_id=auth.uid() or exists(select 1 from public.analyses a join public.analysis_orders o on o.id=a.order_id where a.id=analysis_id and o.user_id=auth.uid())); create policy comments_write on public.timestamp_comments for all using(public.is_admin() or professional_id=auth.uid()) with check(public.is_admin() or professional_id=auth.uid());
create policy notifications_read on public.notifications for select using(user_id=auth.uid() or public.is_admin()); create policy notifications_update on public.notifications for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin()); create policy notifications_admin_insert on public.notifications for insert with check(public.is_admin());

-- Public community and professional marketplace.
create type public.review_request_status as enum ('REQUESTED','ACCEPTED','IN_REVIEW','COMPLETED','DECLINED');
create type public.reaction_type as enum ('LIKE','INSIGHTFUL','FIRE');
create type public.medal_type as enum ('PRECISION','PROGRESS','CONSISTENCY','CRAFT');

alter table public.videos add column is_public boolean not null default false;
alter table public.videos add column caption text;
alter table public.videos add column tags text[] not null default '{}';

create table public.follows (follower_id uuid not null references public.profiles(id) on delete cascade,following_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(follower_id,following_id),check(follower_id <> following_id));
create table public.video_reactions (video_id uuid not null references public.videos(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,reaction public.reaction_type not null default 'LIKE',created_at timestamptz not null default now(),primary key(video_id,user_id));
create table public.video_comments (id uuid primary key default gen_random_uuid(),video_id uuid not null references public.videos(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,body text not null check(char_length(body) between 1 and 1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.video_medals (id uuid primary key default gen_random_uuid(),video_id uuid not null references public.videos(id) on delete cascade,professional_id uuid not null references public.profiles(id) on delete cascade,medal public.medal_type not null,note text check(char_length(note) <= 280),created_at timestamptz not null default now(),unique(video_id,professional_id,medal));
create table public.professional_services (id uuid primary key default gen_random_uuid(),professional_id uuid not null references public.profiles(id) on delete cascade,gig_title text not null default 'Cricket video review',display_name text not null,bio text not null default '',photo_url text,headline text not null default '',specialties text[] not null default '{}',years_experience integer not null default 0 check(years_experience >= 0),turnaround_days integer not null default 3 check(turnaround_days between 1 and 30),review_includes text[] not null default '{}',is_published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.review_requests (id uuid primary key default gen_random_uuid(),requester_id uuid not null references public.profiles(id) on delete cascade,professional_id uuid not null references public.profiles(id) on delete restrict,gig_id uuid references public.professional_services(id) on delete set null,video_id uuid not null references public.videos(id) on delete restrict,status public.review_request_status not null default 'REQUESTED',focus_area text,notes text,overall_score numeric(3,1) check(overall_score between 0 and 10),summary text,strengths text[] not null default '{}',improvements text[] not null default '{}',recommendations text[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),completed_at timestamptz);
create table public.review_timestamp_feedback (id uuid primary key default gen_random_uuid(),review_request_id uuid not null references public.review_requests(id) on delete cascade,professional_id uuid not null references public.profiles(id) on delete cascade,timestamp_seconds integer not null check(timestamp_seconds >= 0),title text not null,feedback text not null,feedback_type public.comment_type not null default 'GENERAL',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index public_videos_idx on public.videos(created_at desc) where is_public and deleted_at is null; create index reviews_requester_idx on public.review_requests(requester_id,status); create index reviews_professional_idx on public.review_requests(professional_id,status); create index comments_video_idx on public.video_comments(video_id,created_at); create index medals_video_idx on public.video_medals(video_id);
create trigger services_updated before update on public.professional_services for each row execute procedure public.set_updated_at(); create trigger video_comments_updated before update on public.video_comments for each row execute procedure public.set_updated_at(); create trigger review_requests_updated before update on public.review_requests for each row execute procedure public.set_updated_at(); create trigger review_feedback_updated before update on public.review_timestamp_feedback for each row execute procedure public.set_updated_at();

create or replace function public.is_verified_professional() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.professional_profiles where user_id=auth.uid() and approved) $$;
create or replace function public.is_review_professional(review_uuid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.review_requests where id=review_uuid and professional_id=auth.uid()) $$;

alter table public.follows enable row level security; alter table public.video_reactions enable row level security; alter table public.video_comments enable row level security; alter table public.video_medals enable row level security; alter table public.professional_services enable row level security; alter table public.review_requests enable row level security; alter table public.review_timestamp_feedback enable row level security;
-- Public videos are readable by everyone authenticated; private videos retain owner/reviewer access.
create policy public_or_owned_videos_read on public.videos for select using(is_public or user_id=auth.uid() or public.is_admin() or exists(select 1 from public.review_requests r where r.video_id=id and r.professional_id=auth.uid()));
create policy follows_read on public.follows for select using(true); create policy follows_write on public.follows for insert with check(follower_id=auth.uid()); create policy follows_delete on public.follows for delete using(follower_id=auth.uid());
create policy reactions_read on public.video_reactions for select using(true); create policy reactions_write on public.video_reactions for insert with check(user_id=auth.uid()); create policy reactions_update on public.video_reactions for update using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy reactions_delete on public.video_reactions for delete using(user_id=auth.uid());
create policy public_comments_read on public.video_comments for select using(exists(select 1 from public.videos v where v.id=video_id and (v.is_public or v.user_id=auth.uid() or public.is_admin()))); create policy comments_create on public.video_comments for insert with check(user_id=auth.uid() and exists(select 1 from public.videos v where v.id=video_id and v.is_public)); create policy comments_manage on public.video_comments for update using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin()); create policy comments_remove on public.video_comments for delete using(user_id=auth.uid() or public.is_admin());
create policy medals_read on public.video_medals for select using(true); create policy medals_award on public.video_medals for insert with check(professional_id=auth.uid() and public.is_verified_professional() and exists(select 1 from public.videos v where v.id=video_id and v.is_public)); create policy medals_remove on public.video_medals for delete using(professional_id=auth.uid() or public.is_admin());
create policy services_read on public.professional_services for select using(is_published or professional_id=auth.uid() or public.is_admin()); create policy services_create on public.professional_services for insert with check(professional_id=auth.uid() and public.is_verified_professional()); create policy services_update on public.professional_services for update using(professional_id=auth.uid() or public.is_admin()) with check(professional_id=auth.uid() or public.is_admin());
create policy reviews_read on public.review_requests for select using(requester_id=auth.uid() or professional_id=auth.uid() or public.is_admin()); create policy reviews_create on public.review_requests for insert with check(requester_id=auth.uid() and exists(select 1 from public.videos v where v.id=video_id and v.user_id=auth.uid()) and exists(select 1 from public.professional_services s where s.professional_id=professional_id and s.is_published)); create policy reviews_requester_update on public.review_requests for update using(requester_id=auth.uid() and status='REQUESTED') with check(requester_id=auth.uid() and status='REQUESTED'); create policy reviews_professional_update on public.review_requests for update using(professional_id=auth.uid() or public.is_admin()) with check(professional_id=auth.uid() or public.is_admin());
create policy review_feedback_read on public.review_timestamp_feedback for select using(public.is_review_professional(review_request_id) or exists(select 1 from public.review_requests r where r.id=review_request_id and r.requester_id=auth.uid()) or public.is_admin()); create policy review_feedback_write on public.review_timestamp_feedback for all using(public.is_review_professional(review_request_id) or public.is_admin()) with check(public.is_review_professional(review_request_id) or public.is_admin());
-- Explicit administrator control for community records.
create policy admin_follows on public.follows for all using(public.is_admin()) with check(public.is_admin()); create policy admin_reactions on public.video_reactions for all using(public.is_admin()) with check(public.is_admin()); create policy admin_comments on public.video_comments for all using(public.is_admin()) with check(public.is_admin()); create policy admin_medals on public.video_medals for all using(public.is_admin()) with check(public.is_admin()); create policy admin_services on public.professional_services for all using(public.is_admin()) with check(public.is_admin()); create policy admin_reviews on public.review_requests for all using(public.is_admin()) with check(public.is_admin()); create policy admin_review_feedback on public.review_timestamp_feedback for all using(public.is_admin()) with check(public.is_admin());

-- MVP self-service professional mode. Users may activate their own professional role once.
create or replace function public.protect_profile_role() returns trigger language plpgsql as $$ begin if new.role is distinct from old.role then if auth.uid() is null then return new; end if; if public.is_admin() then return new; end if; if old.id=auth.uid() and old.role='USER' and new.role='PROFESSIONAL' then return new; end if; raise exception 'Only an account owner may activate professional mode, and only admins may make other role changes'; end if; return new; end; $$;
create or replace function public.is_verified_professional() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('PROFESSIONAL','ADMIN')) $$;
alter table public.professional_profiles alter column approved set default true;

-- Optional local/public banner image for a professional's marketplace service.
alter table public.professional_services add column if not exists banner_url text;

create index professional_services_owner_idx on public.professional_services(professional_id,created_at);
create index review_requests_gig_idx on public.review_requests(gig_id);
create or replace function public.enforce_professional_gig_limit() returns trigger language plpgsql as $$ begin if (select count(*) from public.professional_services where professional_id=new.professional_id)>=3 then raise exception 'A professional may publish up to three gigs.'; end if; return new; end; $$;
create trigger professional_gig_limit before insert on public.professional_services for each row execute procedure public.enforce_professional_gig_limit();
drop policy reviews_create on public.review_requests;
create policy reviews_create on public.review_requests for insert with check(requester_id=auth.uid() and exists(select 1 from public.videos v where v.id=video_id and v.user_id=auth.uid()) and exists(select 1 from public.professional_services s where s.id=gig_id and s.professional_id=professional_id and s.is_published));
