'use client';

import Image from 'next/image';
import { ImagePlus, Trash2 } from 'lucide-react';
import { useRef, useState } from 'react';

export function GigShowcaseUploader({ gigId, galleryUrls = [] }: { gigId: string; galleryUrls?: string[] }) {
  const input = useRef<HTMLInputElement>(null); const [images, setImages] = useState(galleryUrls); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  async function upload(file: File) { setLoading(true); const form = new FormData(); form.append('gig_id', gigId); form.append('file', file); const response = await fetch('/api/professional/gig-media', { method: 'POST', body: form }); const body = await response.json(); setLoading(false); if (body.galleryUrls) setImages(body.galleryUrls); else setMessage(body.error || 'Unable to upload image.'); }
  async function remove(imageUrl: string) { const response = await fetch('/api/professional/gig-media', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ gigId, imageUrl }) }); const body = await response.json(); if (body.galleryUrls) setImages(body.galleryUrls); else setMessage(body.error || 'Unable to remove image.'); }
  return <div><div className="flex items-center justify-between"><div><p className="text-[12px] font-semibold">Work showcase</p><p className="mt-1 text-[11px] text-neutral-400">Add up to 3 images that help players trust your work.</p></div><span className="text-[11px] font-medium text-neutral-400">{images.length}/3</span></div><div className="mt-3 grid grid-cols-3 gap-3">{images.map(imageUrl => <div key={imageUrl} className="group relative aspect-square overflow-hidden rounded-xl bg-neutral-100"><Image src={imageUrl} alt="Coach work sample" fill className="object-cover" /><button onClick={() => remove(imageUrl)} type="button" aria-label="Remove work image" className="absolute right-2 top-2 grid size-7 place-items-center rounded-full bg-black/70 text-white opacity-0 transition group-hover:opacity-100"><Trash2 className="size-3.5" /></button></div>)}{images.length < 3 && <button type="button" onClick={() => input.current?.click()} className="grid aspect-square place-items-center rounded-xl border border-dashed border-black/[.14] bg-neutral-50 text-center"><span><ImagePlus className="mx-auto size-4 text-neutral-400" /><span className="mt-1 block text-[10px] text-neutral-500">Add image</span></span></button>}</div><input ref={input} type="file" className="hidden" accept="image/jpeg,image/png,image/webp" onChange={event => { const file = event.target.files?.[0]; if (file) upload(file); }} />{loading && <p className="mt-2 text-[11px] text-neutral-400">Uploading…</p>}{message && <p className="mt-2 text-[11px] text-red-500">{message}</p>}</div>;
}
