'use client';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { createClient } from '@/lib/supabase/client';
import { registerReviewAttachment, signedReviewAttachments } from '@/lib/reviews/attachments';
import { saveReviewAnnotation } from '@/lib/reviews/actions';
import type { AnnotationObject } from '@/lib/reviews/types';
type Item={id:string;kind:string;mime_type:string;storage_key:string;duration_seconds:number|null;uploaded_by:string;url:string;annotations:{id:string;attachment_id:string;annotation_json:{objects:AnnotationObject[]}}[]};
function shape(o:AnnotationObject,i:number){const x=o.x1*1000,y=o.y1*562,x2=o.x2*1000,y2=o.y2*562;const common={stroke:'#fbbf24',strokeWidth:4,fill:'none'};if(o.type==='circle')return <ellipse key={i} cx={(x+x2)/2} cy={(y+y2)/2} rx={Math.abs(x2-x)/2} ry={Math.abs(y2-y)/2} {...common}/>;if(o.type==='rectangle')return <rect key={i} x={Math.min(x,x2)} y={Math.min(y,y2)} width={Math.abs(x2-x)} height={Math.abs(y2-y)} {...common}/>;return <line key={i} x1={x} y1={y} x2={x2} y2={y2} {...common}/>}
export function ReviewAttachments({reviewId,mode}:{reviewId:string;mode:'coach'|'player'|'report'}){
 const [items,setItems]=useState<Item[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<string|null>(null);const [tool,setTool]=useState<'arrow'|'line'|'circle'|'rectangle'>('arrow');const [objects,setObjects]=useState<AnnotationObject[]>([]);const [anchor,setAnchor]=useState<{x:number;y:number}|null>(null);
 useEffect(()=>{signedReviewAttachments(reviewId).then(setItems).catch(e=>setError(e instanceof Error?e.message:'Attachments unavailable.'))},[reviewId]);
 const upload=async(file:File)=>{setBusy(true);setError('');try{const mime=file.type;let kind:'IMAGE'|'VIDEO'|'AUDIO'|'COACH_VIDEO';if(mime.startsWith('image/'))kind='IMAGE';else if(mime.startsWith('audio/'))kind='AUDIO';else kind=mode==='coach'?'COACH_VIDEO':'VIDEO';if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm','audio/mpeg','audio/mp4','audio/webm'].includes(mime))throw new Error('Unsupported media type.');if(file.size>500*1024*1024)throw new Error('File exceeds 500 MB.');const ext=file.name.split('.').pop()?.replace(/[^a-z0-9]/gi,'').toLowerCase()||'bin';const storageKey=`${reviewId}/${crypto.randomUUID()}.${ext}`;const db=createClient();const {error:uploadError}=await db.storage.from('review-media').upload(storageKey,file,{contentType:mime,upsert:false});if(uploadError)throw new Error(uploadError.message);await registerReviewAttachment({reviewId,kind,storageKey,mimeType:mime,durationSeconds:null});setItems(await signedReviewAttachments(reviewId))}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}};
 const point=(event:React.PointerEvent<SVGSVGElement>)=>{const box=event.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(event.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(event.clientY-box.top)/box.height))}};
 const endShape=(event:React.PointerEvent<SVGSVGElement>)=>{if(!anchor)return;const end=point(event);setObjects(previous=>[...previous,{type:tool,x1:anchor.x,y1:anchor.y,x2:end.x,y2:end.y}]);setAnchor(null)};
 const save=async()=>{if(!selected||!objects.length)return;setBusy(true);try{await saveReviewAnnotation({reviewId,feedbackId:null,attachmentId:selected,timestamp:null,objects});setItems(await signedReviewAttachments(reviewId));setObjects([]);setSelected(null)}catch(e){setError(e instanceof Error?e.message:'Could not save annotation.')}finally{setBusy(false)}};
 return <section className="surface p-5"><h2 className="section-title">{mode==='coach'?'Review attachments':mode==='report'?'Coach media & submitted images':'Your review media'}</h2>{mode!=='report'&&<label className="quiet-button mt-4 inline-flex cursor-pointer">{busy?'Uploading…':mode==='coach'?'Add image, voice note or video response':'Add an image or video'}<input type="file" disabled={busy} className="sr-only" accept={mode==='coach'?'image/jpeg,image/png,image/webp,video/mp4,video/webm,audio/mpeg,audio/mp4,audio/webm':'image/jpeg,image/png,image/webp,video/mp4,video/webm'} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''}}/></label>}{mode==='coach'&&<VoiceRecorder disabled={busy} onRecorded={upload}/>} {error&&<p className="mt-3 text-xs text-red-700" role="alert">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{items.map(item=><div key={item.id} className="overflow-hidden rounded-xl border border-black/8">{item.kind==='IMAGE'?<div className="relative aspect-video bg-neutral-950"><Image src={item.url} alt="Review attachment" fill unoptimized className="object-contain"/><svg viewBox="0 0 1000 562" preserveAspectRatio="none" className={`absolute inset-0 h-full w-full ${mode==='coach'&&selected===item.id?'cursor-crosshair touch-none':'pointer-events-none'}`} onPointerDown={e=>{if(selected===item.id)setAnchor(point(e))}} onPointerUp={e=>{if(selected===item.id)endShape(e)}} aria-label="Image annotations">{item.annotations.flatMap(a=>a.annotation_json.objects).map(shape)}{selected===item.id&&objects.map(shape)}</svg></div>:item.kind==='AUDIO'?<audio controls preload="none" src={item.url} className="w-full p-3"/>:<video controls preload="metadata" src={item.url} className="aspect-video w-full"/>}<div className="p-3"><p className="text-xs font-medium">{item.kind==='COACH_VIDEO'?'Coach video response':item.kind==='AUDIO'?'Voice note':item.kind.toLowerCase()}</p>{mode==='coach'&&item.kind==='IMAGE'&&<button type="button" className="mt-2 text-xs font-medium underline" onClick={()=>{setSelected(item.id);setObjects([])}}>Annotate image</button>}</div></div>)}</div>{selected&&<div className="mt-3 flex flex-wrap items-center gap-2">{(['arrow','line','circle','rectangle'] as const).map(name=><button key={name} type="button" onClick={()=>setTool(name)} className={`quiet-button capitalize ${tool===name?'bg-neutral-900 text-white':''}`}>{name}</button>)}<button type="button" className="quiet-button" onClick={()=>setObjects(objects.slice(0,-1))}>Undo</button><button type="button" className="quiet-button" onClick={()=>setObjects([])}>Clear</button><button type="button" className="primary-button" disabled={!objects.length||busy} onClick={()=>void save()}>Save annotation</button></div>}{!items.length&&<p className="mt-3 text-xs text-neutral-500">No extra media attached.</p>}</section>
}

function VoiceRecorder({ disabled, onRecorded }: { disabled: boolean; onRecorded: (file: File) => Promise<void> }) {
 const [recorder, setRecorder] = useState<MediaRecorder | null>(null); const [recording, setRecording] = useState(false);
 const toggle = async () => { if (recorder) { recorder.stop(); return; } const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const next = new MediaRecorder(stream); const chunks: BlobPart[] = []; next.ondataavailable = event => chunks.push(event.data); next.onstop = () => { stream.getTracks().forEach(track => track.stop()); setRecorder(null); setRecording(false); void onRecorded(new File([new Blob(chunks, { type: next.mimeType || 'audio/webm' })], 'coach-voice-note.webm', { type: next.mimeType || 'audio/webm' })); }; next.start(); setRecorder(next); setRecording(true); };
 return <button type="button" disabled={disabled} onClick={() => void toggle()} className={`quiet-button ml-2 ${recording ? 'bg-red-50 text-red-700' : ''}`}>{recording ? 'Stop recording' : 'Record voice note'}</button>;
}

