'use client';
import { useRef, useState, useTransition } from 'react';
import { Award, MessageCircle } from 'lucide-react';
import Link from 'next/link';
import { markReviewDrill, rateProfessionalReview } from '@/lib/reviews/actions';
import { formatTime } from '@/lib/reviews/rubrics';
import type { Review, ReviewAnnotation, ReviewDrill, RubricScore, TimestampFeedback, ProfessionalMedal, ReviewRating } from '@/lib/reviews/types';
import { ReviewAttachments } from '@/components/review-attachments';
export function ReviewReport({isCoach=false,review,filename,videoUrl,coachName,playerName,serviceName,feedback,scores,annotations,drills:initialDrills,medal,rating,conversationId}:{isCoach?:boolean;review:Review;filename:string;videoUrl:string;coachName:string;playerName:string;serviceName:string;feedback:TimestampFeedback[];scores:RubricScore[];annotations:ReviewAnnotation[];drills:ReviewDrill[];medal:ProfessionalMedal|null;rating:ReviewRating|null;conversationId:string|null}){
 const video=useRef<HTMLVideoElement>(null);const [time,setTime]=useState(0);const [duration,setDuration]=useState(0);const [drills,setDrills]=useState(initialDrills);const [isPending,startTransition]=useTransition();const [error,setError]=useState('');const [ratingForm,setRatingForm]=useState({overall:5,helpfulness:5,clarity:5,wouldBookAgain:true,comment:''});
 const jump=(seconds:number)=>{video.current?.scrollIntoView({behavior:'smooth',block:'center'});if(video.current){video.current.currentTime=seconds;video.current.play().catch(()=>undefined)}setTime(seconds)};
 const activeAnnotation=annotations.filter(item=>item.timestamp_seconds!==null&&Math.abs(item.timestamp_seconds-time)<1)[0];
 return <div className="pb-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Cricket performance report</p><h1 className="page-title mt-2">{serviceName}</h1><p className="page-copy">{playerName} · Reviewed by {coachName} · {new Date(review.completed_at||review.created_at).toLocaleDateString()}</p></div><div className="flex gap-2">{!isCoach&&review.order_id&&<Link className="quiet-button" href={`/reviews/${review.id}/follow-up`}>Submit follow-up</Link>}{conversationId&&<Link className="quiet-button" href={`/messages/${conversationId}`}><MessageCircle className="mr-1 inline size-4"/>Message coach</Link>}</div></div>
 <div className="mt-8 grid gap-4 lg:grid-cols-[.3fr_.7fr]"><div className="surface p-7"><p className="eyebrow">Overall performance</p><p className="mt-5 text-6xl font-semibold tracking-[-.07em]">{review.overall_score??'—'}<span className="ml-2 text-lg text-neutral-400">/ 10</span></p><p className="mt-5 text-xs font-semibold uppercase tracking-wide text-neutral-500">{review.discipline.replaceAll('_',' ')}</p>{medal&&<div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-4"><Award className="size-5 text-amber-700"/><p className="mt-3 text-sm font-semibold">{medal.medal_type.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-neutral-600">Awarded by {coachName}</p><p className="mt-2 text-xs leading-5 text-neutral-600">{medal.reason}</p></div>}</div><div className="surface p-7"><p className="eyebrow">Coach assessment</p><h2 className="mt-4 text-2xl font-semibold leading-tight tracking-tight">{review.summary}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-neutral-400">Strongest area</p><p className="mt-2 text-sm font-medium">{review.strongest_area||'See strengths below'}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-neutral-400">Primary focus</p><p className="mt-2 text-sm font-medium">{review.primary_focus||review.action_plan?.primary_focus||'See action plan below'}</p></div></div></div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(300px,.9fr)]"><div className="space-y-5"><section className="surface overflow-hidden"><div className="relative bg-neutral-950"><video ref={video} src={videoUrl} controls playsInline preload="metadata" className="aspect-video w-full" onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onDurationChange={e=>setDuration(e.currentTarget.duration)} aria-label="Reviewed player video"/>{activeAnnotation&&<svg viewBox="0 0 1000 562" preserveAspectRatio="none" className="pointer-events-none absolute inset-0 h-full w-full">{activeAnnotation.annotation_json.objects.map((o,i)=>{const x=o.x1*1000,y=o.y1*562,x2=o.x2*1000,y2=o.y2*562;if(o.type==='circle')return <ellipse key={i} cx={(x+x2)/2} cy={(y+y2)/2} rx={Math.abs(x2-x)/2} ry={Math.abs(y2-y)/2} stroke="#fbbf24" strokeWidth="3" fill="none"/>;if(o.type==='rectangle')return <rect key={i} x={Math.min(x,x2)} y={Math.min(y,y2)} width={Math.abs(x2-x)} height={Math.abs(y2-y)} stroke="#fbbf24" strokeWidth="3" fill="none"/>;if(o.type==='text')return <text key={i} x={x} y={y} fill="#fbbf24" stroke="#111" strokeWidth="1" fontSize="28" fontWeight="700">{o.label}</text>;if(o.type==='freehand'&&o.points?.length)return <polyline key={i} points={o.points.reduce<string[]>((all,value,index)=>{if(index%2===0)all.push(`${value*1000},${(o.points?.[index+1]||0)*562}`);return all},[]).join(' ')} stroke="#fbbf24" strokeWidth="3" fill="none"/>;return <line key={i} x1={x} y1={y} x2={x2} y2={y2} stroke="#fbbf24" strokeWidth="3"/>})}</svg>}</div><div className="p-4"><p className="text-xs font-medium">{filename}</p><p className="mt-2 text-xs text-neutral-400">Play the video to see the coach&apos;s text and drawing overlays.</p></div></section><ReviewAttachments reviewId={review.id} mode="report"/></div>
 <div className="space-y-5"><section className="surface p-6"><p className="eyebrow">Skill assessment</p><h2 className="section-title mt-2">Rubric scores</h2><div className="mt-5 space-y-4">{scores.filter(s=>s.enabled).map(s=><div key={s.id}><div className="flex items-center justify-between text-xs font-semibold"><span>{s.category_name}</span><span>{s.score??'—'} / 10</span></div><div className="mt-2 h-1.5 rounded-full bg-neutral-100"><div className="h-full rounded-full bg-neutral-800" style={{width:`${Math.max(0,Math.min(100,Number(s.score||0)*10))}%`}}/></div>{s.strength&&<p className="mt-2 text-xs text-neutral-600">{s.strength}</p>}{s.improvement&&<p className="mt-1 text-xs text-neutral-600">Focus: {s.improvement}</p>}{s.recommendation&&<p className="mt-1 text-xs text-neutral-600">Next: {s.recommendation}</p>}</div>)}</div></section><section className="surface p-6"><h2 className="section-title">Coach priorities</h2>{([['Strengths',review.strengths],['Improvements',review.improvements],['Recommendations',review.recommendations]] as const).map(([label,items])=><div className="mt-5" key={label}><p className="text-xs font-semibold uppercase tracking-wide text-neutral-400">{label}</p><ul className="mt-2 space-y-2">{items.filter(Boolean).map((item,i)=><li key={i} className="text-sm leading-6 text-neutral-700">• {item}</li>)}</ul></div>)}{review.coach_closing_note&&<p className="mt-6 border-t border-black/8 pt-5 text-sm leading-6 text-neutral-600">{review.coach_closing_note}</p>}</section><section className="surface p-6"><h2 className="section-title">Training plan</h2><p className="mt-2 text-xs text-neutral-500">{review.action_plan?.duration_days||7} days · {review.action_plan?.primary_focus||review.primary_focus}</p>{review.action_plan?.items?.map((item,i)=><div className="mt-3 flex gap-3 rounded-xl bg-neutral-50 p-3" key={i}><span className="text-xs font-semibold">Day {item.day}</span><span className="text-xs text-neutral-600">{item.title}</span></div>)}<div className="mt-5 space-y-3">{drills.map(d=><label key={d.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-black/8 p-3"><input type="checkbox" checked={d.completed} disabled={isPending||isCoach} onChange={e=>{const checked=e.target.checked;startTransition(async()=>{try{await markReviewDrill(d.id,checked);setDrills(previous=>previous.map(item=>item.id===d.id?{...item,completed:checked}:item))}catch(err){setError(err instanceof Error?err.message:'Could not update drill.')}})}}/><span><span className="block text-xs font-semibold">{d.title}</span><span className="mt-1 block text-xs leading-5 text-neutral-500">{d.instructions}</span><span className="mt-1 block text-[11px] text-neutral-400">{d.target_sets} sets · {d.target_reps} reps · {d.frequency}</span></span></label>)}</div></section></div></div>
 {!isCoach&&!rating&&review.order_id&&<section className="surface mt-5 p-6"><h2 className="section-title">Rate this review</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{(['overall','helpfulness','clarity'] as const).map(key=><label key={key} className="text-xs font-medium capitalize">{key}<select className="mt-1 w-full rounded-xl border border-black/10 p-2.5" value={ratingForm[key]} onChange={e=>setRatingForm({...ratingForm,[key]:Number(e.target.value)})}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label>)}</div><label className="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" checked={ratingForm.wouldBookAgain} onChange={e=>setRatingForm({...ratingForm,wouldBookAgain:e.target.checked})}/> I would book again</label><textarea className="mt-3 min-h-20 w-full rounded-xl border border-black/10 p-3 text-sm" placeholder="What helped you most?" value={ratingForm.comment} onChange={e=>setRatingForm({...ratingForm,comment:e.target.value})}/><button type="button" className="primary-button mt-3" disabled={isPending} onClick={()=>startTransition(async()=>{try{await rateProfessionalReview({reviewId:review.id,...ratingForm});window.location.reload()}catch(err){setError(err instanceof Error?err.message:'Could not save rating.')}})}>Submit rating</button></section>}{rating&&<p className="mt-5 text-xs text-neutral-500">You rated this review {rating.overall_rating} / 5.</p>}{error&&<p className="mt-4 text-xs text-red-700" role="alert">{error}</p>}</div>
}




