import Link from 'next/link';
import { ArrowRight, BadgeCheck, Sparkles } from 'lucide-react';
import { requireUser } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
import { activateProfessionalMode } from './actions';
export default async function ProfilePage(){
 const profile=await requireUser();const db=await createClient();const {data:medals}=await db.from('professional_review_medals').select('id,review_id,medal_type,reason,awarded_at').eq('player_id',profile.id).order('awarded_at',{ascending:false});const isProfessional=profile.role==='PROFESSIONAL'||profile.role==='ADMIN';
 return <><p className="eyebrow">Account</p><h1 className="page-title mt-2">Your profile.</h1><div className="surface mt-8 max-w-2xl overflow-hidden"><div className="flex items-center gap-4 bg-[#f3f4f5] p-7"><span className="grid size-14 place-items-center rounded-full bg-neutral-900 text-lg font-semibold text-white">{profile.full_name?.[0]||profile.email[0]?.toUpperCase()}</span><div><p className="text-lg font-semibold tracking-[-.035em]">{profile.full_name||'Framewise member'}</p><p className="mt-1 text-[12px] text-neutral-500">{profile.email}</p></div></div><div className="p-7"><p className="text-[12px] font-semibold">Current mode</p><div className="mt-3 flex items-center justify-between gap-4"><div><p className="text-[15px] font-semibold">{isProfessional?'Professional':'Member'}</p><p className="mt-1 text-[12px] leading-5 text-neutral-500">{isProfessional?'Your professional workspace and public review service are available.':'Share progress, request reviews, and participate in the community.'}</p></div>{isProfessional?<Link href="/professional" className="quiet-button shrink-0">Open workspace <ArrowRight className="ml-1.5 size-3.5"/></Link>:null}</div></div></div>{!isProfessional?<div className="surface mt-5 max-w-2xl p-7"><span className="grid size-10 place-items-center rounded-xl bg-neutral-100"><Sparkles className="size-4"/></span><h2 className="mt-5 section-title">Switch to professional mode.</h2><p className="mt-2 max-w-lg text-[13px] leading-6 text-neutral-500">Offer video reviews, build a public service, manage your queue, and award rare medals. Professional mode activates instantly during this MVP.</p><form action={activateProfessionalMode}><button className="primary-button mt-6"><BadgeCheck className="mr-1.5 size-3.5"/>Activate professional mode</button></form></div>:null}{medals?.length?<div className="surface mt-5 max-w-2xl p-7"><h2 className="section-title">Professional medals</h2><div className="mt-4 space-y-3">{medals.map(medal=><Link key={medal.id} href={`/reviews/${medal.review_id}`} className="block rounded-xl bg-amber-50 p-4"><p className="text-sm font-semibold">{medal.medal_type.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-neutral-600">{medal.reason}</p></Link>)}</div></div>:null}</>;
}
