'use server';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { requireUser } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
const kind=z.enum(['IMAGE','VIDEO','AUDIO','COACH_VIDEO']);
export async function registerReviewAttachment(input:{reviewId:string;kind:z.infer<typeof kind>;storageKey:string;mimeType:string;durationSeconds:number|null}){const user=await requireUser();const data=z.object({reviewId:z.uuid(),kind,storageKey:z.string().max(300),mimeType:z.string().max(100),durationSeconds:z.number().int().min(0).nullable()}).parse(input);if(!data.storageKey.startsWith(`${data.reviewId}/`))throw new Error('Invalid storage path.');const db=await createClient();const {data:review}=await db.from('review_requests').select('id,requester_id,professional_id,status').eq('id',data.reviewId).single();if(!review||![review.requester_id,review.professional_id].includes(user.id))throw new Error('Review unavailable.');if(data.kind==='COACH_VIDEO'&&user.id!==review.professional_id)throw new Error('Only the coach can add a video response.');if(user.id===review.professional_id&&review.status==='COMPLETED')throw new Error('Submitted review is locked.');const {error}=await db.from('review_attachments').insert({review_id:review.id,uploaded_by:user.id,kind:data.kind,storage_key:data.storageKey,mime_type:data.mimeType,duration_seconds:data.durationSeconds});if(error)throw new Error(error.message);revalidatePath(`/reviews/${review.id}`);revalidatePath(`/professional/reviews/${review.id}`)}
export async function signedReviewAttachments(reviewId:string){const user=await requireUser();const db=await createClient();const {data:review}=await db.from('review_requests').select('id,requester_id,professional_id').eq('id',z.uuid().parse(reviewId)).single();if(!review||![review.requester_id,review.professional_id].includes(user.id))throw new Error('Review unavailable.');const [{data:attachments,error},{data:annotations}]=await Promise.all([db.from('review_attachments').select('id,kind,mime_type,storage_key,duration_seconds,uploaded_by').eq('review_id',review.id).order('created_at'),db.from('review_annotations').select('id,attachment_id,annotation_json').eq('review_id',review.id).not('attachment_id','is',null)]);if(error)throw new Error(error.message);return Promise.all((attachments||[]).map(async item=>{const {data}=await db.storage.from('review-media').createSignedUrl(item.storage_key,3600);return {...item,url:data?.signedUrl||'',annotations:(annotations||[]).filter(a=>a.attachment_id===item.id)}}))}


