import Link from 'next/link';
import { CalendarCheck, CircleDollarSign, ClipboardCheck, Plus, Star } from 'lucide-react';
import { requireProfessional } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';

export default async function CoachDashboard() {
  const coach = await requireProfessional(); const supabase = await createClient();
  const [{ data: orders }, { count: bookings }, { count: reviewRequests }, { data: gigs }, { data: professionalProfile }] = await Promise.all([
    supabase.from('orders').select('id,status,total_cents,created_at,professional_services(gig_title,display_name)').eq('professional_id', coach.id).neq('status', 'DRAFT').order('created_at', { ascending: false }).limit(8),
    supabase.from('bookings').select('*', { count: 'exact', head: true }).eq('professional_id', coach.id).eq('status', 'COMPLETED'),
    supabase.from('review_requests').select('*', { count: 'exact', head: true }).eq('professional_id', coach.id).eq('status', 'REQUESTED'),
    supabase.from('professional_services').select('id,is_published').eq('professional_id', coach.id),
    supabase.from('professional_profiles').select('rating,reviews_completed').eq('user_id', coach.id).maybeSingle(),
  ]);
  const completedOrders = orders?.filter(order => order.status === 'COMPLETED') || []; const earnings = completedOrders.reduce((total, order) => total + order.total_cents, 0);
  const stats = [{ label: 'Bookings completed', value: bookings || 0, icon: CalendarCheck, copy: 'Completed sessions' }, { label: 'Gig purchases', value: orders?.length || 0, icon: ClipboardCheck, copy: 'All purchase requests' }, { label: 'Earnings', value: `NPR ${(earnings / 100).toLocaleString()}`, icon: CircleDollarSign, copy: 'Completed orders' }, { label: 'Coach rating', value: professionalProfile?.rating || '—', icon: Star, copy: `${professionalProfile?.reviews_completed || 0} player ratings` }];
  return <><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Coach dashboard</p><h1 className="page-title mt-2">Your coaching business.</h1><p className="page-copy">Track bookings, revenue, player requests, and the gigs that bring them in.</p></div><Link href="/professional/gigs/new" className="primary-button w-fit"><Plus className="mr-1.5 size-3.5" />Create gig</Link></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon, copy }) => <div key={label} className="surface p-5"><Icon className="size-4 text-neutral-400" /><p className="mt-6 text-3xl font-semibold tracking-[-.05em]">{value}</p><p className="mt-1 text-[11px] text-neutral-600">{label}</p><p className="mt-1 text-[10px] text-neutral-400">{copy}</p></div>)}</div><div className="surface mt-5 flex items-center justify-between bg-[#f7f7f6] p-5"><div><p className="text-[13px] font-semibold">{gigs?.filter(gig => gig.is_published).length || 0} of 3 gigs live</p><p className="mt-1 text-[11px] text-neutral-500">Your new gigs appear in Explore immediately.</p></div><Link href="/professional/gigs" className="quiet-button">Manage gigs</Link></div><section className="mt-10"><div className="flex items-end justify-between"><div><p className="eyebrow">New activity</p><h2 className="section-title mt-2">Purchases and review requests</h2></div><Link href="/professional/reviews" className="text-[12px] font-medium text-neutral-500">Open review queue →</Link></div><div className="surface mt-5 divide-y divide-black/[.055]">{orders?.length ? orders.map((order:any) => <Link key={order.id} href="/notifications" className="flex items-center justify-between gap-4 p-5 transition hover:bg-neutral-50 active:scale-[.995]"><div><p className="text-[13px] font-semibold">{order.professional_services?.gig_title || 'Gig purchase'}</p><p className="mt-1 text-[11px] text-neutral-400">{order.professional_services?.display_name || 'Player purchase'} · {new Date(order.created_at).toLocaleDateString()}</p></div><span className="rounded-full bg-neutral-100 px-3 py-1 text-[10px] font-semibold">{order.status.replaceAll('_', ' ')}</span></Link>) : <div className="p-8 text-center"><p className="text-[13px] font-semibold">No purchases yet.</p><p className="mt-1 text-[12px] text-neutral-500">Publish a gig so players can find you in Explore.</p></div>}</div>{reviewRequests ? <p className="mt-3 text-[11px] font-medium text-amber-700">{reviewRequests} review request{reviewRequests === 1 ? '' : 's'} need your attention.</p> : null}</section></>;
}
